services:
  eswms.api:
    image: ${DOCKER_REGISTRY-}eswmsapi:latest
    container_name: eswms_api
    build:
      context: .
      dockerfile: src/Server/esWMS.API/Dockerfile

  eswms.client:
    image: ${DOCKER_REGISTRY-}eswms:latest
    container_name: eswms_client
    build:
      context: .
      dockerfile: src/Client/esWMS/Dockerfile

  db:
    container_name: eswms_db
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Strong@Passw0rd
      MYSQL_DATABASE: esWMS
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
