version: '3.4'

services:
  eswmsapi:
    volumes:
      - ./src/Server/esWMS.API:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  eswmsclient:
    volumes:
      - ./src/Client/esWMS:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  db:
    volumes:
      - db_data:/var/lib/mysql